### ISSUE TITLE
Landscaper CLI for local usage

### ISSUE THREAD

**Issue by In-Ko** [gardener/landscapercli#3]
**Description**
In order to improve & simplify the way endusers work with the Landscaper, we need to provide an easy to consume, well documented and stable Command Line Interface for the Landscaper Core.
This Epic gathers the first set of tasks which we have to address, focusing on local usecases.

**Scope / Features to be covered by this Epic**
In a first meeting, it has been discussed what the CLI should provide short- to midterm:
- Enable easy "jump start" for local development scenarios via some kind of `landscaper init` command
- Simplify the process of creating a first blueprint and/or component descriptor, based on a template, using a command like `landscaper create component`
- Provide means to validate local landscaper artefacts

**SubTasks**
- [x] [Move existing Landscaper CLI Code to Potter Repo](https://github.com/gardener/landscapercli/issues/6)
- [x] [CLI Command "landscaper quickstart"](https://github.com/gardener/landscapercli/issues/5)
- [x] [CLI Test Suite](https://github.com/gardener/landscapercli/issues/4)
- [x] [Integrate Component CLI](https://github.com/gardener/landscapercli/issues/13)
- [x] [CLI Command "create component"](https://github.com/gardener/landscapercli/issues/7)
- [x] [CLI Command "create installation"](https://github.com/gardener/landscapercli/issues/21)
- [x] [CLI Commands for debugging](https://github.com/gardener/landscapercli/issues/8)
- [x] [CLI Command "validate local"](https://github.com/gardener/landscapercli/issues/2)

**Comment by In-Ko** [comment]
This Epic is done. Further Requirements towards the landscaper CLI will be tracked in separate issues.
