### ISSUE TITLE
Build Landscaper Components for a first minimum initial set of Gardener Components

### ISSUE THREAD

**Issue by In-Ko** [gardener/landscapercli#58]
**Description**
We need to start modelling first Landscaper-based Components (blueprints, component descriptors) for an initial set of existing Gardener Components. The "initial set" has been discussed in a meeting:

- dns + garden (virtual, but not system-components/nginx; becomes virtual garden cluster; a start was made by Rafael, see here: https://github.com/gardener/virtual-garden
- gardener-extensions (just dns-external)
- gardener-extensions (just networking-calico)
- gardener-extensions (just os-gardenlinux)
- gardener-extensions (just provider-aws; a beginning was made in https://github.com/gardener/gardener-extension-provider-aws/tree/master/.landscaper)
- gardenlet (below gardener). This is already worked on by Daniel.
- gardener (everything but gardenlet below gardener)

- For each of these components, a dedicated task will be created and referenced in this epic. Those tasks will also include the work that has to be done in 'landscape-setup' (e.g. using the new landscaper-components there), possibly followed later by adopting this in the 'garden-setup'
- This initial set has to fulfil the requirement to enable full testing within the Gardener test-machinery whenever a new PR is created for a new Gardener-Version. We will also try to clarify this in the mentioned meeting. Also this work will then be further detailed out in a dedicated task, linked to this epic.

Done Criteria for this Epic:
- [ ] The initial set of Gardener Components has been modelled consistently in terms of Landscaper Artefacts like blueprints and component descriptors
- [ ] This set of new Landscaper Components has been added to 'landscape-setup' and the relevant old parts for those components have been deleted from 'landscape-setup', so that only the landscaper artefacts (in the end installation.yamls) are used to deploy those Gardener components.
- [ ] Integration of these new Landscaper Components into the test-machinery has been done, enabling testability / validation of new PRs for new Gardener-Versions.

**SubTasks**
- [x] [Knowledge Build-up 'Gardener Components'](https://github.com/gardener/landscapercli/issues/56)
- [x] [Knowledge Build-up 'landscape-setup'](https://github.com/gardener/landscapercli/issues/57)
- [x] [Setup of central Landscaper Instances](https://github.com/gardener/landscapercli/issues/69)
- [ ] [Enable Copying of local resources to LSSD](https://github.com/gardener/landscapercli/issues/70)
- [x] [Create Landscaper Component for "dns-external" gardener-extension](https://github.com/gardener/landscapercli/issues/64)
- [ ] [Create Landscaper Component for "provider-aws" gardener-extension](https://github.com/gardener/landscapercli/issues/65)
- [ ] [Create Landscaper Component for "Virtual Garden Cluster"](https://github.com/gardener/landscapercli/issues/63)
- [ ] [How-To Guide "Initial Modelling and Dev-Workflow for Landscaper Components"](https://github.com/gardener/landscapercli/issues/74)

**Comment by vlerenc** [comment]
@In-Ko The main goal is indeed PR validation using these new components/blueprints and then also integration into the current landscape installation, but that's actually `landscape-setup` (this one drives our landscapes) and not `garden-setup` (this ones drives/is the community installer), but that can be a follow-up goal to also make the first step towards a new community installer. Then the team should take over/get involved to migrate the remaining components for both `setup`s.

**Comment by In-Ko** [comment]
I have changed the description in the Epic accordingly, thanks for the hint.

**Comment by jschicktanz** [comment]
@enrico-kaack-comp and me worked on the following components:
  - dns-external
  - networking-calico
  - os-gardenlinux

current status: the PRs are open in the component repositories and require review

**Comment by In-Ko** [comment]
@jschicktanz , @enrico-kaack-comp, @robertgraeff , @achimweigel : Can you guys please also update the initial task description above in terms of ticking off what has been finished. I believe setting up the landscaper instances on the various landscapes is by done, same for the copying of local resources ? Also the two extensions are ready, right ? ...

**Comment by achimweigel** [comment]
@In-Ko should we close this?

**Comment by In-Ko** [comment]
Yes.
